[project]
name = "warframe-dmg-parser"
version = "0.2.0"
description = "Parses Warframe's EE.log for high damage events"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.15.0",
]
